In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
import os
from os import listdir
from os.path import isfile, join

In [3]:
p = "C:/Users/user/Desktop/Project Stuff/dataset/"

In [4]:
for f in listdir(p):
    print(f)

.directory
0
1
2
3
4
5
6
7
8
9
add
dec
div
eq
mul
sub
x
y
z

In [5]:
import cv2

In [6]:
#loading images
def load_images(folder):
    train_data=[]
    for filename in listdir(folder):

        if filename != ".directory" :

            image = cv2.imread(os.path.join(folder,filename),cv2.IMREAD_GRAYSCALE)
            image = ~image

            if image is not None:

                ret, thresh = cv2.threshold(image,127,255,cv2.THRESH_BINARY)
                contours, hierarchy = cv2.findContours(thresh,cv2.RETR_EXTERNAL,cv2.CHAIN_APPROX_NONE)
                contour = sorted(contours, key = lambda ctr: cv2.boundingRect(ctr)[0])

                a = int(28)
                b = int(28)
                maxi = 0

                for c in contour:

                    x,y,a,b=cv2.boundingRect(c)
                    maxi=max(a*b,maxi)

                    if maxi==a*b:

                        x_max=x
                        y_max=y
                        w_max=a
                        h_max=b

                im_crop = thresh[y_max:y_max+h_max+10, x_max:x_max+w_max+10]
                im_resize = cv2.resize(im_crop,(28,28))
                im_resize = np.reshape(im_resize,(784,1))
                train_data.append(im_resize)
            
    return train_data

In [7]:
data = []

data = load_images(p+"0")
for i in range(0, len(data)):
    data[i] = np.append(data[i], ['0'])
print(len(data))

595

In [8]:
iter = 0
for i in list(os.listdir(p)) :
    if i not in ["0", ".directory"] :
        print("Iter :", iter)
        print("Working with the", i, "folder")
        data_i = load_images(p+i)
        if i in [str(k) for k in range(1, 10)] :
            for j in range(0, len(data_i)):
                data_i[j] = np.append(data_i[j], [i])
        if i == "add" :
            for j in range(0, len(data_i)):
                data_i[j] = np.append(data_i[j], ["10"])
        if i == "sub" :
            for j in range(0, len(data_i)):
                data_i[j] = np.append(data_i[j], ["11"])
        if i == "mul" :
            for j in range(0, len(data_i)):
                data_i[j] = np.append(data_i[j], ["12"])
        if i == "div" :
            for j in range(0, len(data_i)):
                data_i[j] = np.append(data_i[j], ["13"])
        if i == "eq" :
            for j in range(0, len(data_i)):
                data_i[j] = np.append(data_i[j], ["14"])                
        if i == "dec" :
            for j in range(0, len(data_i)):
                data_i[j] = np.append(data_i[j], ["15"])
        if i == "x" :
            for j in range(0, len(data_i)):
                data_i[j] = np.append(data_i[j], ["16"])
        if i == "y" :
            for j in range(0, len(data_i)):
                data_i[j] = np.append(data_i[j], ["17"]) 
        if i == "z" :
            for j in range(0, len(data_i)):
                data_i[j] = np.append(data_i[j], ["18"]) 
        data = np.concatenate((data, data_i))
        print(len(data))
        print()
        iter += 1

Iter : 0
Working with the 1 folder
1157

Iter : 1
Working with the 2 folder
1590

Iter : 2
Working with the 3 folder
2131

Iter : 3
Working with the 4 folder
2657

Iter : 4
Working with the 5 folder
3090

Iter : 5
Working with the 6 folder
3671

Iter : 6
Working with the 7 folder
4204

Iter : 7
Working with the 8 folder
4758

Iter : 8
Working with the 9 folder
5304

Iter : 9
Working with the add folder
5900

Iter : 10
Working with the dec folder
6524

Iter : 11
Working with the div folder
7142

Iter : 12
Working with the eq folder
7776

Iter : 13
Working with the mul folder
8353

Iter : 14
Working with the sub folder
9008

Iter : 15
Working with the x folder
9460

Iter : 16
Working with the y folder
9859

Iter : 17
Working with the z folder
10071

In [9]:
df = pd.DataFrame(data, index=None)

In [10]:
df.to_csv('train.csv',index=False)

In [11]:
DF = pd.read_csv('train.csv')

In [12]:
DF.head()

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,784
0,0,0,0,0,0,0,0,168,255,255,...,0,0,0,0,0,0,0,0,0,0
1,0,0,209,255,255,255,255,255,255,255,...,0,0,0,0,0,0,0,0,0,0
2,0,122,255,255,255,255,255,255,255,255,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,65,255,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,110,137,...,0,0,0,0,0,0,0,0,0,0

In [13]:
DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10071 entries, 0 to 10070
Columns: 785 entries, 0 to 784
dtypes: int64(785)
memory usage: 60.3 MB

In [14]:
DF.describe()

,0,1,2,3,4,5,6,7,8,9,...,775,776,777,778,779,780,781,782,783,784
count,10071.000000,10071.000000,10071.000000,10071.000000,10071.000000,10071.000000,10071.000000,10071.000000,10071.000000,10071.000000,...,10071.000000,10071.000000,10071.000000,10071.000000,10071.000000,10071.000000,10071.000000,10071.000000,10071.000000,10071.000000
mean,14.504021,31.573925,35.525668,40.711151,47.526065,53.905769,59.889385,66.965843,75.295601,81.090458,...,1.870122,1.732003,1.455168,1.448516,1.233840,1.095125,1.042598,0.756727,0.661305,8.745209
std,53.523002,80.484808,84.751010,89.993530,95.542453,100.198675,104.087922,107.825836,111.883093,114.231478,...,21.113558,20.345178,18.637720,18.758940,17.105033,16.205222,15.758797,13.399039,12.590012,5.213059
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,9.000000
75%,0.000000,0.000000,0.000000,0.000000,0.000000,7.500000,73.000000,168.500000,241.000000,255.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,13.000000
max,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,...,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,255.000000,18.000000

In [15]:
DF.shape

(10071, 785)

In [16]:
labels = DF[['784']]

In [17]:
labels

       784
0        0
1        0
2        0
3        0
4        0
...    ...
10066   18
10067   18
10068   18
10069   18
10070   18

[10071 rows x 1 columns]

In [18]:
DF.drop(DF.columns[[784]], axis=1, inplace=True)

In [19]:
DF.shape

(10071, 784)

In [20]:
DF.head(5)

,0,1,2,3,4,5,6,7,8,9,...,774,775,776,777,778,779,780,781,782,783
0,0,0,0,0,0,0,0,168,255,255,...,0,0,0,0,0,0,0,0,0,0
1,0,0,209,255,255,255,255,255,255,255,...,0,0,0,0,0,0,0,0,0,0
2,0,122,255,255,255,255,255,255,255,255,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,65,255,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,110,137,...,0,0,0,0,0,0,0,0,0,0

In [21]:
labels = np.array(labels)

In [22]:
labels.shape

(10071, 1)

In [23]:
from keras.utils.np_utils import to_categorical

In [24]:
cat = to_categorical(labels, num_classes=19)

In [25]:
cat.shape

(10071, 19)

In [26]:
cat[4]

array([1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0.], dtype=float32)

In [27]:
temp=DF.to_numpy()
Xtrain = temp.reshape(temp.shape[0], 28, 28, 1)
Xtrain.shape

(10071, 28, 28, 1)

In [28]:
l=[]
for i in range(Xtrain.shape[0]):
    l.append(np.array(DF[i:i+1]).reshape(1,28,28))

np.random.seed(7)

In [29]:
from keras.models import Sequential

In [30]:
from keras.layers.convolutional import Conv2D, MaxPooling2D

In [31]:
from keras.layers import Input, Dense, Dropout, Flatten

In [32]:
#compiling model
Model = Sequential()

In [33]:
Model.add(Conv2D(32, (3,3), input_shape=(28, 28, 1), activation='relu',padding='same'))
Model.add(MaxPooling2D(pool_size=(2, 2)))
Model.add(Conv2D(15, (3, 3), activation='relu'))
Model.add(MaxPooling2D(pool_size=(2, 2)))
Model.add(Dropout(0.2))
Model.add(Flatten())
Model.add(Dense(128, activation='relu'))
Model.add(Dense(50, activation='relu'))
Model.add(Dense(19, activation='softmax'))

In [34]:
Model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 conv2d (Conv2D)             (None, 28, 28, 32)        320

 max_pooling2d (MaxPooling2D  (None, 14, 14, 32)       0
 )

 conv2d_1 (Conv2D)           (None, 12, 12, 15)        4335

 max_pooling2d_1 (MaxPooling  (None, 6, 6, 15)         0
 2D)

 dropout (Dropout)           (None, 6, 6, 15)          0

 flatten (Flatten)           (None, 540)               0

 dense (Dense)               (None, 128)               69248

 dense_1 (Dense)             (None, 50)                6450

 dense_2 (Dense)             (None, 19)                969

=================================================================
Total params: 81,322
Trainable params: 81,322
Non-trainable params: 0
_________________________________________________________________

In [53]:
from keras.callbacks import ModelCheckpoint

In [54]:
checkpoint = ModelCheckpoint("saved_model.h5", monitor='accuracy', verbose=1, save_best_only=True)

In [55]:
Model.compile(loss="categorical_crossentropy", optimizer='Adam', metrics=['accuracy'])
nn = Model.fit(Xtrain, cat, epochs=50, batch_size=256, shuffle=True, verbose=1, callbacks=[checkpoint])

Epoch 1/50
40/40 [==============================] - ETA: 0s - loss: 0.0696 - accuracy: 0.9717
Epoch 1: accuracy improved from -inf to 0.97170, saving model to saved_model.h5
40/40 [==============================] - 5s 124ms/step - loss: 0.0696 - accuracy: 0.9717
Epoch 2/50
39/40 [============================>.] - ETA: 0s - loss: 0.0585 - accuracy: 0.9785
Epoch 2: accuracy improved from 0.97170 to 0.97855, saving model to saved_model.h5
40/40 [==============================] - 5s 123ms/step - loss: 0.0582 - accuracy: 0.9786
Epoch 3/50
40/40 [==============================] - ETA: 0s - loss: 0.0524 - accuracy: 0.9794
Epoch 3: accuracy improved from 0.97855 to 0.97945, saving model to saved_model.h5
40/40 [==============================] - 5s 122ms/step - loss: 0.0524 - accuracy: 0.9794
Epoch 4/50
40/40 [==============================] - ETA: 0s - loss: 0.0565 - accuracy: 0.9794
Epoch 4: accuracy did not improve from 0.97945
40/40 [==============================] - 5s 121ms/step - loss: 0.0565 - accuracy: 0.9794
Epoch 5/50
40/40 [==============================] - ETA: 0s - loss: 0.0602 - accuracy: 0.9760
Epoch 5: accuracy did not improve from 0.97945
40/40 [==============================] - 5s 120ms/step - loss: 0.0602 - accuracy: 0.9760
Epoch 6/50
40/40 [==============================] - ETA: 0s - loss: 0.0485 - accuracy: 0.9803
Epoch 6: accuracy improved from 0.97945 to 0.98034, saving model to saved_model.h5
40/40 [==============================] - 5s 122ms/step - loss: 0.0485 - accuracy: 0.9803
Epoch 7/50
40/40 [==============================] - ETA: 0s - loss: 0.0461 - accuracy: 0.9822
Epoch 7: accuracy improved from 0.98034 to 0.98223, saving model to saved_model.h5
40/40 [==============================] - 5s 124ms/step - loss: 0.0461 - accuracy: 0.9822
Epoch 8/50
39/40 [============================>.] - ETA: 0s - loss: 0.0527 - accuracy: 0.9811
Epoch 8: accuracy did not improve from 0.98223
40/40 [==============================] - 5s 123ms/step - loss: 0.0530 - accuracy: 0.9809
Epoch 9/50
40/40 [==============================] - ETA: 0s - loss: 0.0617 - accuracy: 0.9785
Epoch 9: accuracy did not improve from 0.98223
40/40 [==============================] - 5s 122ms/step - loss: 0.0617 - accuracy: 0.9785
Epoch 10/50
40/40 [==============================] - ETA: 0s - loss: 0.0546 - accuracy: 0.9786
Epoch 10: accuracy did not improve from 0.98223
40/40 [==============================] - 5s 123ms/step - loss: 0.0546 - accuracy: 0.9786
Epoch 11/50
40/40 [==============================] - ETA: 0s - loss: 0.0521 - accuracy: 0.9789
Epoch 11: accuracy did not improve from 0.98223
40/40 [==============================] - 5s 122ms/step - loss: 0.0521 - accuracy: 0.9789
Epoch 12/50
40/40 [==============================] - ETA: 0s - loss: 0.0469 - accuracy: 0.9825
Epoch 12: accuracy improved from 0.98223 to 0.98252, saving model to saved_model.h5
40/40 [==============================] - 5s 126ms/step - loss: 0.0469 - accuracy: 0.9825
Epoch 13/50
40/40 [==============================] - ETA: 0s - loss: 0.0488 - accuracy: 0.9812
Epoch 13: accuracy did not improve from 0.98252
40/40 [==============================] - 5s 124ms/step - loss: 0.0488 - accuracy: 0.9812
Epoch 14/50
40/40 [==============================] - ETA: 0s - loss: 0.0422 - accuracy: 0.9845
Epoch 14: accuracy improved from 0.98252 to 0.98451, saving model to saved_model.h5
40/40 [==============================] - 5s 122ms/step - loss: 0.0422 - accuracy: 0.9845
Epoch 15/50
39/40 [============================>.] - ETA: 0s - loss: 0.0494 - accuracy: 0.9833
Epoch 15: accuracy did not improve from 0.98451
40/40 [==============================] - 5s 123ms/step - loss: 0.0494 - accuracy: 0.9831
Epoch 16/50
39/40 [============================>.] - ETA: 0s - loss: 0.0438 - accuracy: 0.9837
Epoch 16: accuracy did not improve from 0.98451
40/40 [==============================] - 5s 121ms/step - loss: 0.0435 - accuracy: 0.9838
Epoch 17/50
40/40 [==============================] - ETA: 0s - loss: 0.0432 - accuracy: 0.9847
Epoch 17: accuracy improved from 0.98451 to 0.98471, saving model to saved_model.h5
40/40 [==============================] - 5s 126ms/step - loss: 0.0432 - accuracy: 0.9847
Epoch 18/50
40/40 [==============================] - ETA: 0s - loss: 0.0433 - accuracy: 0.9838
Epoch 18: accuracy did not improve from 0.98471
40/40 [==============================] - 5s 121ms/step - loss: 0.0433 - accuracy: 0.9838
Epoch 19/50
39/40 [============================>.] - ETA: 0s - loss: 0.0387 - accuracy: 0.9848
Epoch 19: accuracy did not improve from 0.98471
40/40 [==============================] - 5s 135ms/step - loss: 0.0388 - accuracy: 0.9847
Epoch 20/50
40/40 [==============================] - ETA: 0s - loss: 0.0359 - accuracy: 0.9873
Epoch 20: accuracy improved from 0.98471 to 0.98729, saving model to saved_model.h5
40/40 [==============================] - 5s 127ms/step - loss: 0.0359 - accuracy: 0.9873
Epoch 21/50
40/40 [==============================] - ETA: 0s - loss: 0.0352 - accuracy: 0.9867
Epoch 21: accuracy did not improve from 0.98729
40/40 [==============================] - 5s 124ms/step - loss: 0.0352 - accuracy: 0.9867
Epoch 22/50
40/40 [==============================] - ETA: 0s - loss: 0.0355 - accuracy: 0.9882
Epoch 22: accuracy improved from 0.98729 to 0.98818, saving model to saved_model.h5
40/40 [==============================] - 5s 127ms/step - loss: 0.0355 - accuracy: 0.9882
Epoch 23/50
40/40 [==============================] - ETA: 0s - loss: 0.0366 - accuracy: 0.9866
Epoch 23: accuracy did not improve from 0.98818
40/40 [==============================] - 5s 124ms/step - loss: 0.0366 - accuracy: 0.9866
Epoch 24/50
40/40 [==============================] - ETA: 0s - loss: 0.0358 - accuracy: 0.9869
Epoch 24: accuracy did not improve from 0.98818
40/40 [==============================] - 5s 123ms/step - loss: 0.0358 - accuracy: 0.9869
Epoch 25/50
40/40 [==============================] - ETA: 0s - loss: 0.0314 - accuracy: 0.9896
Epoch 25: accuracy improved from 0.98818 to 0.98957, saving model to saved_model.h5
40/40 [==============================] - 5s 125ms/step - loss: 0.0314 - accuracy: 0.9896
Epoch 26/50
40/40 [==============================] - ETA: 0s - loss: 0.0353 - accuracy: 0.9877
Epoch 26: accuracy did not improve from 0.98957
40/40 [==============================] - 5s 126ms/step - loss: 0.0353 - accuracy: 0.9877
Epoch 27/50
40/40 [==============================] - ETA: 0s - loss: 0.0338 - accuracy: 0.9890
Epoch 27: accuracy did not improve from 0.98957
40/40 [==============================] - 5s 130ms/step - loss: 0.0338 - accuracy: 0.9890
Epoch 28/50
40/40 [==============================] - ETA: 0s - loss: 0.0399 - accuracy: 0.9855
Epoch 28: accuracy did not improve from 0.98957
40/40 [==============================] - 5s 129ms/step - loss: 0.0399 - accuracy: 0.9855
Epoch 29/50
40/40 [==============================] - ETA: 0s - loss: 0.0351 - accuracy: 0.9885
Epoch 29: accuracy did not improve from 0.98957
40/40 [==============================] - 5s 135ms/step - loss: 0.0351 - accuracy: 0.9885
Epoch 30/50
40/40 [==============================] - ETA: 0s - loss: 0.0306 - accuracy: 0.9899
Epoch 30: accuracy improved from 0.98957 to 0.98987, saving model to saved_model.h5
40/40 [==============================] - 5s 131ms/step - loss: 0.0306 - accuracy: 0.9899
Epoch 31/50
40/40 [==============================] - ETA: 0s - loss: 0.0320 - accuracy: 0.9888
Epoch 31: accuracy did not improve from 0.98987
40/40 [==============================] - 5s 131ms/step - loss: 0.0320 - accuracy: 0.9888
Epoch 32/50
40/40 [==============================] - ETA: 0s - loss: 0.0256 - accuracy: 0.9921
Epoch 32: accuracy improved from 0.98987 to 0.99206, saving model to saved_model.h5
40/40 [==============================] - 5s 136ms/step - loss: 0.0256 - accuracy: 0.9921
Epoch 33/50
40/40 [==============================] - ETA: 0s - loss: 0.0296 - accuracy: 0.9896
Epoch 33: accuracy did not improve from 0.99206
40/40 [==============================] - 5s 136ms/step - loss: 0.0296 - accuracy: 0.9896
Epoch 34/50
40/40 [==============================] - ETA: 0s - loss: 0.0356 - accuracy: 0.9872
Epoch 34: accuracy did not improve from 0.99206
40/40 [==============================] - 5s 134ms/step - loss: 0.0356 - accuracy: 0.9872
Epoch 35/50
40/40 [==============================] - ETA: 0s - loss: 0.0377 - accuracy: 0.9867
Epoch 35: accuracy did not improve from 0.99206
40/40 [==============================] - 5s 132ms/step - loss: 0.0377 - accuracy: 0.9867
Epoch 36/50
40/40 [==============================] - ETA: 0s - loss: 0.0368 - accuracy: 0.9872
Epoch 36: accuracy did not improve from 0.99206
40/40 [==============================] - 5s 130ms/step - loss: 0.0368 - accuracy: 0.9872
Epoch 37/50
40/40 [==============================] - ETA: 0s - loss: 0.0327 - accuracy: 0.9884
Epoch 37: accuracy did not improve from 0.99206
40/40 [==============================] - 5s 130ms/step - loss: 0.0327 - accuracy: 0.9884
Epoch 38/50
40/40 [==============================] - ETA: 0s - loss: 0.0308 - accuracy: 0.9890
Epoch 38: accuracy did not improve from 0.99206
40/40 [==============================] - 5s 132ms/step - loss: 0.0308 - accuracy: 0.9890
Epoch 39/50
40/40 [==============================] - ETA: 0s - loss: 0.0301 - accuracy: 0.9892
Epoch 39: accuracy did not improve from 0.99206
40/40 [==============================] - 6s 149ms/step - loss: 0.0301 - accuracy: 0.9892
Epoch 40/50
40/40 [==============================] - ETA: 0s - loss: 0.0292 - accuracy: 0.9907
Epoch 40: accuracy did not improve from 0.99206
40/40 [==============================] - 6s 137ms/step - loss: 0.0292 - accuracy: 0.9907
Epoch 41/50
40/40 [==============================] - ETA: 0s - loss: 0.0270 - accuracy: 0.9894
Epoch 41: accuracy did not improve from 0.99206
40/40 [==============================] - 6s 140ms/step - loss: 0.0270 - accuracy: 0.9894
Epoch 42/50
40/40 [==============================] - ETA: 0s - loss: 0.0253 - accuracy: 0.9910
Epoch 42: accuracy did not improve from 0.99206
40/40 [==============================] - 5s 137ms/step - loss: 0.0253 - accuracy: 0.9910
Epoch 43/50
40/40 [==============================] - ETA: 0s - loss: 0.0337 - accuracy: 0.9882
Epoch 43: accuracy did not improve from 0.99206
40/40 [==============================] - 5s 132ms/step - loss: 0.0337 - accuracy: 0.9882
Epoch 44/50
40/40 [==============================] - ETA: 0s - loss: 0.0300 - accuracy: 0.9892
Epoch 44: accuracy did not improve from 0.99206
40/40 [==============================] - 5s 129ms/step - loss: 0.0300 - accuracy: 0.9892
Epoch 45/50
40/40 [==============================] - ETA: 0s - loss: 0.0308 - accuracy: 0.9903
Epoch 45: accuracy did not improve from 0.99206
40/40 [==============================] - 5s 130ms/step - loss: 0.0308 - accuracy: 0.9903
Epoch 46/50
40/40 [==============================] - ETA: 0s - loss: 0.0350 - accuracy: 0.9890
Epoch 46: accuracy did not improve from 0.99206
40/40 [==============================] - 5s 130ms/step - loss: 0.0350 - accuracy: 0.9890
Epoch 47/50
40/40 [==============================] - ETA: 0s - loss: 0.0270 - accuracy: 0.9920
Epoch 47: accuracy did not improve from 0.99206
40/40 [==============================] - 5s 131ms/step - loss: 0.0270 - accuracy: 0.9920
Epoch 48/50
40/40 [==============================] - ETA: 0s - loss: 0.0223 - accuracy: 0.9929
Epoch 48: accuracy improved from 0.99206 to 0.99285, saving model to saved_model.h5
40/40 [==============================] - 5s 132ms/step - loss: 0.0223 - accuracy: 0.9929
Epoch 49/50
40/40 [==============================] - ETA: 0s - loss: 0.0257 - accuracy: 0.9917
Epoch 49: accuracy did not improve from 0.99285
40/40 [==============================] - 5s 135ms/step - loss: 0.0257 - accuracy: 0.9917
Epoch 50/50
40/40 [==============================] - ETA: 0s - loss: 0.0232 - accuracy: 0.9923
Epoch 50: accuracy did not improve from 0.99285
40/40 [==============================] - 5s 134ms/step - loss: 0.0232 - accuracy: 0.9923